/*
 * cvr.dev API dokumentation
 *
 * # Introduktion Velkommen til [cvr.dev](https://cvr.dev)'s HTTP API dokumentation.  Dette dokument beskriver, hvordan du kan benytte vores API til at hente CVR-data. Vi henter og cacher data fra Virks CVR-database en gang i minuttet, så vi altid kan levere så nøjagtig data som muligt.  Udover at være beskrevet på denne sige, er vores API også [beskrevet i OpenAPI 3.0 format](https://docs.cvr.dev/cvrdev_openapi.yml) og som [Postman-dokumentation](https://documenter.getpostman.com/view/13435475/TVejiqUr).  For at benytte vores API skal du have en [cvr.dev-konto](https://cvr.dev/#/auth/signup) med et aktivt abonnement, som du kan [prøve gratis de første 30 dage](https://cvr.dev/#/prices). 
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Tidsperiode hvori noget har været (eller stadig er) gældende. Når gyldigTil er null, er perioden endnu ikke slut.  Det er uklart hvad det betyder, når gyldigFra er null. 
    /// </summary>
    [DataContract(Name = "Periode")]
    public partial class Periode : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Periode" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Periode() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Periode" /> class.
        /// </summary>
        /// <param name="gyldigFra">Startdato for perioden  (required).</param>
        /// <param name="gyldigTil">Slutdato for perioden. Hvis null, bør perioden endnu ikke være afsluttet  (required).</param>
        public Periode(string gyldigFra = default(string), string gyldigTil = default(string))
        {
            // to ensure "gyldigFra" is required (not null)
            if (gyldigFra == null)
            {
                throw new ArgumentNullException("gyldigFra is a required property for Periode and cannot be null");
            }
            this.GyldigFra = gyldigFra;
            // to ensure "gyldigTil" is required (not null)
            if (gyldigTil == null)
            {
                throw new ArgumentNullException("gyldigTil is a required property for Periode and cannot be null");
            }
            this.GyldigTil = gyldigTil;
        }

        /// <summary>
        /// Startdato for perioden 
        /// </summary>
        /// <value>Startdato for perioden </value>
        /// <example>1990-01-08</example>
        [DataMember(Name = "gyldigFra", IsRequired = true, EmitDefaultValue = true)]
        public string GyldigFra { get; set; }

        /// <summary>
        /// Slutdato for perioden. Hvis null, bør perioden endnu ikke være afsluttet 
        /// </summary>
        /// <value>Slutdato for perioden. Hvis null, bør perioden endnu ikke være afsluttet </value>
        /// <example>2018-05-21</example>
        [DataMember(Name = "gyldigTil", IsRequired = true, EmitDefaultValue = true)]
        public string GyldigTil { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Periode {\n");
            sb.Append("  GyldigFra: ").Append(GyldigFra).Append("\n");
            sb.Append("  GyldigTil: ").Append(GyldigTil).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
