/*
 * cvr.dev API dokumentation
 *
 * # Introduktion Velkommen til [cvr.dev](https://cvr.dev)'s HTTP API dokumentation.  Dette dokument beskriver, hvordan du kan benytte vores API til at hente CVR-data. Vi henter og cacher data fra Virks CVR-database en gang i minuttet, så vi altid kan levere så nøjagtig data som muligt.  Udover at være beskrevet på denne sige, er vores API også [beskrevet i OpenAPI 3.0 format](https://docs.cvr.dev/cvrdev_openapi.yml) og som [Postman-dokumentation](https://documenter.getpostman.com/view/13435475/TVejiqUr).  For at benytte vores API skal du have en [cvr.dev-konto](https://cvr.dev/#/auth/signup) med et aktivt abonnement, som du kan [prøve gratis de første 30 dage](https://cvr.dev/#/prices). 
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// En opsummering af den gældende information vedrørende produktionsenheden. Dette er meget ofte denne information, man ønsker at benytte. 
    /// </summary>
    [DataContract(Name = "Produktionsenhed_produktionsEnhedMetadata")]
    public partial class ProduktionsenhedProduktionsEnhedMetadata : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProduktionsenhedProduktionsEnhedMetadata" /> class.
        /// </summary>
        /// <param name="nyesteAarsbeskaeftigelse">nyesteAarsbeskaeftigelse.</param>
        /// <param name="nyesteBeliggenhedsadresse">nyesteBeliggenhedsadresse.</param>
        /// <param name="nyesteBibranche1">nyesteBibranche1.</param>
        /// <param name="nyesteBibranche2">nyesteBibranche2.</param>
        /// <param name="nyesteBibranche3">nyesteBibranche3.</param>
        /// <param name="nyesteCvrNummerRelation">nyesteCvrNummerRelation.</param>
        /// <param name="nyesteHovedbranche">nyesteHovedbranche.</param>
        /// <param name="nyesteKontaktoplysninger">Kan indeholde enhver form for kontaktoplysning, e.g. email adresse, telefonnummer, postadresse. .</param>
        /// <param name="nyesteKvartalsbeskaeftigelse">nyesteKvartalsbeskaeftigelse.</param>
        /// <param name="nyesteNavn">nyesteNavn.</param>
        /// <param name="sammensatStatus">sammensatStatus.</param>
        public ProduktionsenhedProduktionsEnhedMetadata(VirksomhedVirksomhedMetadataNyesteAarsbeskaeftigelse nyesteAarsbeskaeftigelse = default(VirksomhedVirksomhedMetadataNyesteAarsbeskaeftigelse), VirksomhedVirksomhedMetadataNyesteBeliggenhedsadresse nyesteBeliggenhedsadresse = default(VirksomhedVirksomhedMetadataNyesteBeliggenhedsadresse), VirksomhedVirksomhedMetadataNyesteBibranche1 nyesteBibranche1 = default(VirksomhedVirksomhedMetadataNyesteBibranche1), VirksomhedVirksomhedMetadataNyesteBibranche1 nyesteBibranche2 = default(VirksomhedVirksomhedMetadataNyesteBibranche1), VirksomhedVirksomhedMetadataNyesteBibranche1 nyesteBibranche3 = default(VirksomhedVirksomhedMetadataNyesteBibranche1), long? nyesteCvrNummerRelation = default(long?), VirksomhedVirksomhedMetadataNyesteBibranche1 nyesteHovedbranche = default(VirksomhedVirksomhedMetadataNyesteBibranche1), List<string> nyesteKontaktoplysninger = default(List<string>), VirksomhedVirksomhedMetadataNyesteKvartalsbeskaeftigelse nyesteKvartalsbeskaeftigelse = default(VirksomhedVirksomhedMetadataNyesteKvartalsbeskaeftigelse), VirksomhedVirksomhedMetadataNyesteNavn nyesteNavn = default(VirksomhedVirksomhedMetadataNyesteNavn), string sammensatStatus = default(string))
        {
            this.NyesteAarsbeskaeftigelse = nyesteAarsbeskaeftigelse;
            this.NyesteBeliggenhedsadresse = nyesteBeliggenhedsadresse;
            this.NyesteBibranche1 = nyesteBibranche1;
            this.NyesteBibranche2 = nyesteBibranche2;
            this.NyesteBibranche3 = nyesteBibranche3;
            this.NyesteCvrNummerRelation = nyesteCvrNummerRelation;
            this.NyesteHovedbranche = nyesteHovedbranche;
            this.NyesteKontaktoplysninger = nyesteKontaktoplysninger;
            this.NyesteKvartalsbeskaeftigelse = nyesteKvartalsbeskaeftigelse;
            this.NyesteNavn = nyesteNavn;
            this.SammensatStatus = sammensatStatus;
        }

        /// <summary>
        /// Gets or Sets NyesteAarsbeskaeftigelse
        /// </summary>
        [DataMember(Name = "nyesteAarsbeskaeftigelse", EmitDefaultValue = false)]
        public VirksomhedVirksomhedMetadataNyesteAarsbeskaeftigelse NyesteAarsbeskaeftigelse { get; set; }

        /// <summary>
        /// Gets or Sets NyesteBeliggenhedsadresse
        /// </summary>
        [DataMember(Name = "nyesteBeliggenhedsadresse", EmitDefaultValue = false)]
        public VirksomhedVirksomhedMetadataNyesteBeliggenhedsadresse NyesteBeliggenhedsadresse { get; set; }

        /// <summary>
        /// Gets or Sets NyesteBibranche1
        /// </summary>
        [DataMember(Name = "nyesteBibranche1", EmitDefaultValue = false)]
        public VirksomhedVirksomhedMetadataNyesteBibranche1 NyesteBibranche1 { get; set; }

        /// <summary>
        /// Gets or Sets NyesteBibranche2
        /// </summary>
        [DataMember(Name = "nyesteBibranche2", EmitDefaultValue = false)]
        public VirksomhedVirksomhedMetadataNyesteBibranche1 NyesteBibranche2 { get; set; }

        /// <summary>
        /// Gets or Sets NyesteBibranche3
        /// </summary>
        [DataMember(Name = "nyesteBibranche3", EmitDefaultValue = false)]
        public VirksomhedVirksomhedMetadataNyesteBibranche1 NyesteBibranche3 { get; set; }

        /// <summary>
        /// Gets or Sets NyesteCvrNummerRelation
        /// </summary>
        /// <example>24213714</example>
        [DataMember(Name = "nyesteCvrNummerRelation", EmitDefaultValue = true)]
        public long? NyesteCvrNummerRelation { get; set; }

        /// <summary>
        /// Gets or Sets NyesteHovedbranche
        /// </summary>
        [DataMember(Name = "nyesteHovedbranche", EmitDefaultValue = false)]
        public VirksomhedVirksomhedMetadataNyesteBibranche1 NyesteHovedbranche { get; set; }

        /// <summary>
        /// Kan indeholde enhver form for kontaktoplysning, e.g. email adresse, telefonnummer, postadresse. 
        /// </summary>
        /// <value>Kan indeholde enhver form for kontaktoplysning, e.g. email adresse, telefonnummer, postadresse. </value>
        [DataMember(Name = "nyesteKontaktoplysninger", EmitDefaultValue = false)]
        public List<string> NyesteKontaktoplysninger { get; set; }

        /// <summary>
        /// Gets or Sets NyesteKvartalsbeskaeftigelse
        /// </summary>
        [DataMember(Name = "nyesteKvartalsbeskaeftigelse", EmitDefaultValue = false)]
        public VirksomhedVirksomhedMetadataNyesteKvartalsbeskaeftigelse NyesteKvartalsbeskaeftigelse { get; set; }

        /// <summary>
        /// Gets or Sets NyesteNavn
        /// </summary>
        [DataMember(Name = "nyesteNavn", EmitDefaultValue = false)]
        public VirksomhedVirksomhedMetadataNyesteNavn NyesteNavn { get; set; }

        /// <summary>
        /// Gets or Sets SammensatStatus
        /// </summary>
        /// <example>Ophørt</example>
        [DataMember(Name = "sammensatStatus", EmitDefaultValue = false)]
        public string SammensatStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProduktionsenhedProduktionsEnhedMetadata {\n");
            sb.Append("  NyesteAarsbeskaeftigelse: ").Append(NyesteAarsbeskaeftigelse).Append("\n");
            sb.Append("  NyesteBeliggenhedsadresse: ").Append(NyesteBeliggenhedsadresse).Append("\n");
            sb.Append("  NyesteBibranche1: ").Append(NyesteBibranche1).Append("\n");
            sb.Append("  NyesteBibranche2: ").Append(NyesteBibranche2).Append("\n");
            sb.Append("  NyesteBibranche3: ").Append(NyesteBibranche3).Append("\n");
            sb.Append("  NyesteCvrNummerRelation: ").Append(NyesteCvrNummerRelation).Append("\n");
            sb.Append("  NyesteHovedbranche: ").Append(NyesteHovedbranche).Append("\n");
            sb.Append("  NyesteKontaktoplysninger: ").Append(NyesteKontaktoplysninger).Append("\n");
            sb.Append("  NyesteKvartalsbeskaeftigelse: ").Append(NyesteKvartalsbeskaeftigelse).Append("\n");
            sb.Append("  NyesteNavn: ").Append(NyesteNavn).Append("\n");
            sb.Append("  SammensatStatus: ").Append(SammensatStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
