/*
 * cvr.dev API dokumentation
 *
 * # Introduktion Velkommen til [cvr.dev](https://cvr.dev)'s HTTP API dokumentation.  Dette dokument beskriver, hvordan du kan benytte vores API til at hente CVR-data. Vi henter og cacher data fra Virks CVR-database en gang i minuttet, så vi altid kan levere så nøjagtig data som muligt.  Udover at være beskrevet på denne sige, er vores API også [beskrevet i OpenAPI 3.0 format](https://docs.cvr.dev/cvrdev_openapi.yml) og som [Postman-dokumentation](https://documenter.getpostman.com/view/13435475/TVejiqUr).  For at benytte vores API skal du have en [cvr.dev-konto](https://cvr.dev/#/auth/signup) med et aktivt abonnement, som du kan [prøve gratis de første 30 dage](https://cvr.dev/#/prices). 
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// RegNummer
    /// </summary>
    [DataContract(Name = "RegNummer")]
    public partial class RegNummer : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RegNummer" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RegNummer() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RegNummer" /> class.
        /// </summary>
        /// <param name="periode">periode (required).</param>
        /// <param name="sidstOpdateret">Seneste tidspunkt hvor dette objekt blev opdateret  (required).</param>
        /// <param name="regnummer">Vær opmærksom på at feltet regNummer også eksisterer. Dette navn bliver ikke benyttet konsistent. .</param>
        /// <param name="varRegNummer">Vær opmærksom på at feltet regnummer også eksisterer. Dette navn bliver ikke benyttet konsistent. .</param>
        public RegNummer(Periode periode = default(Periode), string sidstOpdateret = default(string), string regnummer = default(string), string varRegNummer = default(string))
        {
            // to ensure "periode" is required (not null)
            if (periode == null)
            {
                throw new ArgumentNullException("periode is a required property for RegNummer and cannot be null");
            }
            this.Periode = periode;
            // to ensure "sidstOpdateret" is required (not null)
            if (sidstOpdateret == null)
            {
                throw new ArgumentNullException("sidstOpdateret is a required property for RegNummer and cannot be null");
            }
            this.SidstOpdateret = sidstOpdateret;
            this.Regnummer = regnummer;
            this.VarRegNummer = varRegNummer;
        }

        /// <summary>
        /// Gets or Sets Periode
        /// </summary>
        [DataMember(Name = "periode", IsRequired = true, EmitDefaultValue = true)]
        public Periode Periode { get; set; }

        /// <summary>
        /// Seneste tidspunkt hvor dette objekt blev opdateret 
        /// </summary>
        /// <value>Seneste tidspunkt hvor dette objekt blev opdateret </value>
        /// <example>2020-04-08T00:10:47.000Z</example>
        [DataMember(Name = "sidstOpdateret", IsRequired = true, EmitDefaultValue = true)]
        public string SidstOpdateret { get; set; }

        /// <summary>
        /// Vær opmærksom på at feltet regNummer også eksisterer. Dette navn bliver ikke benyttet konsistent. 
        /// </summary>
        /// <value>Vær opmærksom på at feltet regNummer også eksisterer. Dette navn bliver ikke benyttet konsistent. </value>
        /// <example>A/S45999</example>
        [DataMember(Name = "regnummer", EmitDefaultValue = false)]
        public string Regnummer { get; set; }

        /// <summary>
        /// Vær opmærksom på at feltet regnummer også eksisterer. Dette navn bliver ikke benyttet konsistent. 
        /// </summary>
        /// <value>Vær opmærksom på at feltet regnummer også eksisterer. Dette navn bliver ikke benyttet konsistent. </value>
        /// <example>A/S45999</example>
        [DataMember(Name = "regNummer", EmitDefaultValue = false)]
        public string VarRegNummer { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RegNummer {\n");
            sb.Append("  Periode: ").Append(Periode).Append("\n");
            sb.Append("  SidstOpdateret: ").Append(SidstOpdateret).Append("\n");
            sb.Append("  Regnummer: ").Append(Regnummer).Append("\n");
            sb.Append("  VarRegNummer: ").Append(VarRegNummer).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
