/*
 * cvr.dev API dokumentation
 *
 * # Introduktion Velkommen til [cvr.dev](https://cvr.dev)'s HTTP API dokumentation.  Dette dokument beskriver, hvordan du kan benytte vores API til at hente CVR-data. Vi henter og cacher data fra Virks CVR-database en gang i minuttet, så vi altid kan levere så nøjagtig data som muligt.  Udover at være beskrevet på denne sige, er vores API også [beskrevet i OpenAPI 3.0 format](https://docs.cvr.dev/cvrdev_openapi.yml) og som [Postman-dokumentation](https://documenter.getpostman.com/view/13435475/TVejiqUr).  For at benytte vores API skal du have en [cvr.dev-konto](https://cvr.dev/#/auth/signup) med et aktivt abonnement, som du kan [prøve gratis de første 30 dage](https://cvr.dev/#/prices). 
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Ejerskabsrelation mellem en enhed (person eller virksomhed) og en virksomhed. Enheden ejer virksomheden. 
    /// </summary>
    [DataContract(Name = "VirksomhedOwnership")]
    public partial class VirksomhedOwnership : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VirksomhedOwnership" /> class.
        /// </summary>
        /// <param name="ejerEnhedsnummer">Ejerens enhedsnummer.</param>
        /// <param name="ejerNavn">Ejerens navn.</param>
        /// <param name="ejerCvrNummer">Ejerens CVR-nummer, hvis enheden er en virksomhed. Vil være null for enheder, der ikke er virksomheder.</param>
        /// <param name="ejerEnhedstype">Ejerens enhedstype: VIRKSOMHED, PERSON eller ANDEN_DELTAGER.</param>
        /// <param name="ejerforhold">Ejerforhold: &#39;Reel ejer&#39; eller &#39;Legal ejer&#39;.</param>
        /// <param name="virksomhedEnhedsnummer">Virksomhedens enhedsnummer.</param>
        /// <param name="virksomhedNavn">Virksomhedens navn.</param>
        /// <param name="virksomhedCvrNummer">Virksomhedens CVR nummer.</param>
        /// <param name="virksomhedsform">Virksomhedens virksomhedsform, e.g. APS, A/S.</param>
        /// <param name="ejerandel">Andel af ejerskab, angivet i intervallet [0;1].</param>
        /// <param name="ejerandelGyldigFra">Dato hvor nyeste ejerskab startede.</param>
        /// <param name="ejerandelGyldigTil">Dato hvor nyeste ejerskab sluttede. Vil være null ved igangværende ejerskab.</param>
        /// <param name="stemmeret">Andel af stemmerettigheder, angivet i intervallet [0;1].</param>
        /// <param name="stemmeretGyldigFra">Dato hvor nyeste stemmerettigheder startede.</param>
        /// <param name="stemmeretGyldigTil">Dato hvor stemmerettigheder sluttede. Vil være null ved igangværende stemmerettigheder.</param>
        /// <param name="distance">Ejerskabsdistancen mellem enheden, der blev slået op, og ejerskabet af denne virksomhed.</param>
        public VirksomhedOwnership(long ejerEnhedsnummer = default(long), string ejerNavn = default(string), long? ejerCvrNummer = default(long?), string ejerEnhedstype = default(string), string ejerforhold = default(string), int virksomhedEnhedsnummer = default(int), string virksomhedNavn = default(string), long virksomhedCvrNummer = default(long), string virksomhedsform = default(string), string ejerandel = default(string), DateTime ejerandelGyldigFra = default(DateTime), DateTime? ejerandelGyldigTil = default(DateTime?), string stemmeret = default(string), DateTime stemmeretGyldigFra = default(DateTime), DateTime? stemmeretGyldigTil = default(DateTime?), int distance = default(int))
        {
            this.EjerEnhedsnummer = ejerEnhedsnummer;
            this.EjerNavn = ejerNavn;
            this.EjerCvrNummer = ejerCvrNummer;
            this.EjerEnhedstype = ejerEnhedstype;
            this.Ejerforhold = ejerforhold;
            this.VirksomhedEnhedsnummer = virksomhedEnhedsnummer;
            this.VirksomhedNavn = virksomhedNavn;
            this.VirksomhedCvrNummer = virksomhedCvrNummer;
            this.Virksomhedsform = virksomhedsform;
            this.Ejerandel = ejerandel;
            this.EjerandelGyldigFra = ejerandelGyldigFra;
            this.EjerandelGyldigTil = ejerandelGyldigTil;
            this.Stemmeret = stemmeret;
            this.StemmeretGyldigFra = stemmeretGyldigFra;
            this.StemmeretGyldigTil = stemmeretGyldigTil;
            this.Distance = distance;
        }

        /// <summary>
        /// Ejerens enhedsnummer
        /// </summary>
        /// <value>Ejerens enhedsnummer</value>
        /// <example>2337773</example>
        [DataMember(Name = "ejer_enhedsnummer", EmitDefaultValue = false)]
        public long EjerEnhedsnummer { get; set; }

        /// <summary>
        /// Ejerens navn
        /// </summary>
        /// <value>Ejerens navn</value>
        /// <example>NOVO NORDISK FONDEN</example>
        [DataMember(Name = "ejer_navn", EmitDefaultValue = false)]
        public string EjerNavn { get; set; }

        /// <summary>
        /// Ejerens CVR-nummer, hvis enheden er en virksomhed. Vil være null for enheder, der ikke er virksomheder
        /// </summary>
        /// <value>Ejerens CVR-nummer, hvis enheden er en virksomhed. Vil være null for enheder, der ikke er virksomheder</value>
        /// <example>10582989</example>
        [DataMember(Name = "ejer_cvr_nummer", EmitDefaultValue = true)]
        public long? EjerCvrNummer { get; set; }

        /// <summary>
        /// Ejerens enhedstype: VIRKSOMHED, PERSON eller ANDEN_DELTAGER
        /// </summary>
        /// <value>Ejerens enhedstype: VIRKSOMHED, PERSON eller ANDEN_DELTAGER</value>
        /// <example>VIRKSOMHED</example>
        [DataMember(Name = "ejer_enhedstype", EmitDefaultValue = false)]
        public string EjerEnhedstype { get; set; }

        /// <summary>
        /// Ejerforhold: &#39;Reel ejer&#39; eller &#39;Legal ejer&#39;
        /// </summary>
        /// <value>Ejerforhold: &#39;Reel ejer&#39; eller &#39;Legal ejer&#39;</value>
        /// <example>Legal ejer</example>
        [DataMember(Name = "ejerforhold", EmitDefaultValue = false)]
        public string Ejerforhold { get; set; }

        /// <summary>
        /// Virksomhedens enhedsnummer
        /// </summary>
        /// <value>Virksomhedens enhedsnummer</value>
        /// <example>4010032536</example>
        [DataMember(Name = "virksomhed_enhedsnummer", EmitDefaultValue = false)]
        public int VirksomhedEnhedsnummer { get; set; }

        /// <summary>
        /// Virksomhedens navn
        /// </summary>
        /// <value>Virksomhedens navn</value>
        /// <example>NNF Kenya A/S</example>
        [DataMember(Name = "virksomhed_navn", EmitDefaultValue = false)]
        public string VirksomhedNavn { get; set; }

        /// <summary>
        /// Virksomhedens CVR nummer
        /// </summary>
        /// <value>Virksomhedens CVR nummer</value>
        /// <example>44790718</example>
        [DataMember(Name = "virksomhed_cvr_nummer", EmitDefaultValue = false)]
        public long VirksomhedCvrNummer { get; set; }

        /// <summary>
        /// Virksomhedens virksomhedsform, e.g. APS, A/S
        /// </summary>
        /// <value>Virksomhedens virksomhedsform, e.g. APS, A/S</value>
        /// <example>A/S</example>
        [DataMember(Name = "virksomhedsform", EmitDefaultValue = false)]
        public string Virksomhedsform { get; set; }

        /// <summary>
        /// Andel af ejerskab, angivet i intervallet [0;1]
        /// </summary>
        /// <value>Andel af ejerskab, angivet i intervallet [0;1]</value>
        /// <example>1.0</example>
        [DataMember(Name = "ejerandel", EmitDefaultValue = false)]
        public string Ejerandel { get; set; }

        /// <summary>
        /// Dato hvor nyeste ejerskab startede
        /// </summary>
        /// <value>Dato hvor nyeste ejerskab startede</value>
        /// <example>2024-04-23T00:00Z</example>
        [DataMember(Name = "ejerandel_gyldig_fra", EmitDefaultValue = false)]
        public DateTime EjerandelGyldigFra { get; set; }

        /// <summary>
        /// Dato hvor nyeste ejerskab sluttede. Vil være null ved igangværende ejerskab
        /// </summary>
        /// <value>Dato hvor nyeste ejerskab sluttede. Vil være null ved igangværende ejerskab</value>
        [DataMember(Name = "ejerandel_gyldig_til", EmitDefaultValue = true)]
        public DateTime? EjerandelGyldigTil { get; set; }

        /// <summary>
        /// Andel af stemmerettigheder, angivet i intervallet [0;1]
        /// </summary>
        /// <value>Andel af stemmerettigheder, angivet i intervallet [0;1]</value>
        /// <example>1.0</example>
        [DataMember(Name = "stemmeret", EmitDefaultValue = false)]
        public string Stemmeret { get; set; }

        /// <summary>
        /// Dato hvor nyeste stemmerettigheder startede
        /// </summary>
        /// <value>Dato hvor nyeste stemmerettigheder startede</value>
        /// <example>2024-04-23T00:00Z</example>
        [DataMember(Name = "stemmeret_gyldig_fra", EmitDefaultValue = false)]
        public DateTime StemmeretGyldigFra { get; set; }

        /// <summary>
        /// Dato hvor stemmerettigheder sluttede. Vil være null ved igangværende stemmerettigheder
        /// </summary>
        /// <value>Dato hvor stemmerettigheder sluttede. Vil være null ved igangværende stemmerettigheder</value>
        [DataMember(Name = "stemmeret_gyldig_til", EmitDefaultValue = true)]
        public DateTime? StemmeretGyldigTil { get; set; }

        /// <summary>
        /// Ejerskabsdistancen mellem enheden, der blev slået op, og ejerskabet af denne virksomhed
        /// </summary>
        /// <value>Ejerskabsdistancen mellem enheden, der blev slået op, og ejerskabet af denne virksomhed</value>
        /// <example>3</example>
        [DataMember(Name = "distance", EmitDefaultValue = false)]
        public int Distance { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VirksomhedOwnership {\n");
            sb.Append("  EjerEnhedsnummer: ").Append(EjerEnhedsnummer).Append("\n");
            sb.Append("  EjerNavn: ").Append(EjerNavn).Append("\n");
            sb.Append("  EjerCvrNummer: ").Append(EjerCvrNummer).Append("\n");
            sb.Append("  EjerEnhedstype: ").Append(EjerEnhedstype).Append("\n");
            sb.Append("  Ejerforhold: ").Append(Ejerforhold).Append("\n");
            sb.Append("  VirksomhedEnhedsnummer: ").Append(VirksomhedEnhedsnummer).Append("\n");
            sb.Append("  VirksomhedNavn: ").Append(VirksomhedNavn).Append("\n");
            sb.Append("  VirksomhedCvrNummer: ").Append(VirksomhedCvrNummer).Append("\n");
            sb.Append("  Virksomhedsform: ").Append(Virksomhedsform).Append("\n");
            sb.Append("  Ejerandel: ").Append(Ejerandel).Append("\n");
            sb.Append("  EjerandelGyldigFra: ").Append(EjerandelGyldigFra).Append("\n");
            sb.Append("  EjerandelGyldigTil: ").Append(EjerandelGyldigTil).Append("\n");
            sb.Append("  Stemmeret: ").Append(Stemmeret).Append("\n");
            sb.Append("  StemmeretGyldigFra: ").Append(StemmeretGyldigFra).Append("\n");
            sb.Append("  StemmeretGyldigTil: ").Append(StemmeretGyldigTil).Append("\n");
            sb.Append("  Distance: ").Append(Distance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
