/*
 * cvr.dev API dokumentation
 *
 * # Introduktion Velkommen til [cvr.dev](https://cvr.dev)'s HTTP API dokumentation.  Dette dokument beskriver, hvordan du kan benytte vores API til at hente CVR-data. Vi henter og cacher data fra Virks CVR-database en gang i minuttet, så vi altid kan levere så nøjagtig data som muligt.  Udover at være beskrevet på denne sige, er vores API også [beskrevet i OpenAPI 3.0 format](https://docs.cvr.dev/cvrdev_openapi.yml) og som [Postman-dokumentation](https://documenter.getpostman.com/view/13435475/TVejiqUr).  For at benytte vores API skal du have en [cvr.dev-konto](https://cvr.dev/#/auth/signup) med et aktivt abonnement, som du kan [prøve gratis de første 30 dage](https://cvr.dev/#/prices). 
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// VirksomhedStatusInner
    /// </summary>
    [DataContract(Name = "Virksomhed_status_inner")]
    public partial class VirksomhedStatusInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VirksomhedStatusInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VirksomhedStatusInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VirksomhedStatusInner" /> class.
        /// </summary>
        /// <param name="kreditoplysningkode">Vær opmærksom på at feltet kreditoplysningskode også eksisterer. Disse bliver ikke benyttet konsekvent i datasettet. .</param>
        /// <param name="kreditoplysningtekst">Vær opmærksom på at feltet kreditoplysningstekst også eksisterer. Disse bliver ikke benyttet konsekvent i datasettet. .</param>
        /// <param name="kreditoplysningskode">Vær opmærksom på at feltet kreditoplysningkode også eksisterer. Disse bliver ikke benyttet konsekvent i datasettet. .</param>
        /// <param name="kreditoplysningstekst">Vær opmærksom på at feltet kreditoplysningtekst også eksisterer. Disse bliver ikke benyttet konsekvent i datasettet. .</param>
        /// <param name="periode">periode (required).</param>
        /// <param name="sidstOpdateret">Seneste tidspunkt hvor dette objekt blev opdateret  (required).</param>
        /// <param name="statuskode">statuskode (required).</param>
        /// <param name="statustekst">statustekst (required).</param>
        public VirksomhedStatusInner(long kreditoplysningkode = default(long), string kreditoplysningtekst = default(string), long kreditoplysningskode = default(long), string kreditoplysningstekst = default(string), Periode periode = default(Periode), string sidstOpdateret = default(string), long statuskode = default(long), string statustekst = default(string))
        {
            // to ensure "periode" is required (not null)
            if (periode == null)
            {
                throw new ArgumentNullException("periode is a required property for VirksomhedStatusInner and cannot be null");
            }
            this.Periode = periode;
            // to ensure "sidstOpdateret" is required (not null)
            if (sidstOpdateret == null)
            {
                throw new ArgumentNullException("sidstOpdateret is a required property for VirksomhedStatusInner and cannot be null");
            }
            this.SidstOpdateret = sidstOpdateret;
            this.Statuskode = statuskode;
            // to ensure "statustekst" is required (not null)
            if (statustekst == null)
            {
                throw new ArgumentNullException("statustekst is a required property for VirksomhedStatusInner and cannot be null");
            }
            this.Statustekst = statustekst;
            this.Kreditoplysningkode = kreditoplysningkode;
            this.Kreditoplysningtekst = kreditoplysningtekst;
            this.Kreditoplysningskode = kreditoplysningskode;
            this.Kreditoplysningstekst = kreditoplysningstekst;
        }

        /// <summary>
        /// Vær opmærksom på at feltet kreditoplysningskode også eksisterer. Disse bliver ikke benyttet konsekvent i datasettet. 
        /// </summary>
        /// <value>Vær opmærksom på at feltet kreditoplysningskode også eksisterer. Disse bliver ikke benyttet konsekvent i datasettet. </value>
        /// <example>0</example>
        [DataMember(Name = "kreditoplysningkode", EmitDefaultValue = false)]
        public long Kreditoplysningkode { get; set; }

        /// <summary>
        /// Vær opmærksom på at feltet kreditoplysningstekst også eksisterer. Disse bliver ikke benyttet konsekvent i datasettet. 
        /// </summary>
        /// <value>Vær opmærksom på at feltet kreditoplysningstekst også eksisterer. Disse bliver ikke benyttet konsekvent i datasettet. </value>
        /// <example>Konkurs</example>
        [DataMember(Name = "kreditoplysningtekst", EmitDefaultValue = true)]
        public string Kreditoplysningtekst { get; set; }

        /// <summary>
        /// Vær opmærksom på at feltet kreditoplysningkode også eksisterer. Disse bliver ikke benyttet konsekvent i datasettet. 
        /// </summary>
        /// <value>Vær opmærksom på at feltet kreditoplysningkode også eksisterer. Disse bliver ikke benyttet konsekvent i datasettet. </value>
        /// <example>0</example>
        [DataMember(Name = "kreditoplysningskode", EmitDefaultValue = false)]
        public long Kreditoplysningskode { get; set; }

        /// <summary>
        /// Vær opmærksom på at feltet kreditoplysningtekst også eksisterer. Disse bliver ikke benyttet konsekvent i datasettet. 
        /// </summary>
        /// <value>Vær opmærksom på at feltet kreditoplysningtekst også eksisterer. Disse bliver ikke benyttet konsekvent i datasettet. </value>
        /// <example>Konkurs</example>
        [DataMember(Name = "kreditoplysningstekst", EmitDefaultValue = true)]
        public string Kreditoplysningstekst { get; set; }

        /// <summary>
        /// Gets or Sets Periode
        /// </summary>
        [DataMember(Name = "periode", IsRequired = true, EmitDefaultValue = true)]
        public Periode Periode { get; set; }

        /// <summary>
        /// Seneste tidspunkt hvor dette objekt blev opdateret 
        /// </summary>
        /// <value>Seneste tidspunkt hvor dette objekt blev opdateret </value>
        /// <example>2020-04-08T00:10:47.000Z</example>
        [DataMember(Name = "sidstOpdateret", IsRequired = true, EmitDefaultValue = true)]
        public string SidstOpdateret { get; set; }

        /// <summary>
        /// Gets or Sets Statuskode
        /// </summary>
        /// <example>5</example>
        [DataMember(Name = "statuskode", IsRequired = true, EmitDefaultValue = true)]
        public long Statuskode { get; set; }

        /// <summary>
        /// Gets or Sets Statustekst
        /// </summary>
        /// <example>Regnskab og boafslutning</example>
        [DataMember(Name = "statustekst", IsRequired = true, EmitDefaultValue = true)]
        public string Statustekst { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VirksomhedStatusInner {\n");
            sb.Append("  Kreditoplysningkode: ").Append(Kreditoplysningkode).Append("\n");
            sb.Append("  Kreditoplysningtekst: ").Append(Kreditoplysningtekst).Append("\n");
            sb.Append("  Kreditoplysningskode: ").Append(Kreditoplysningskode).Append("\n");
            sb.Append("  Kreditoplysningstekst: ").Append(Kreditoplysningstekst).Append("\n");
            sb.Append("  Periode: ").Append(Periode).Append("\n");
            sb.Append("  SidstOpdateret: ").Append(SidstOpdateret).Append("\n");
            sb.Append("  Statuskode: ").Append(Statuskode).Append("\n");
            sb.Append("  Statustekst: ").Append(Statustekst).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
