/*
 * cvr.dev API dokumentation
 *
 * # Introduktion Velkommen til [cvr.dev](https://cvr.dev)'s HTTP API dokumentation.  Dette dokument beskriver, hvordan du kan benytte vores API til at hente CVR-data. Vi henter og cacher data fra Virks CVR-database en gang i minuttet, så vi altid kan levere så nøjagtig data som muligt.  Udover at være beskrevet på denne sige, er vores API også [beskrevet i OpenAPI 3.0 format](https://docs.cvr.dev/cvrdev_openapi.yml) og som [Postman-dokumentation](https://documenter.getpostman.com/view/13435475/TVejiqUr).  For at benytte vores API skal du have en [cvr.dev-konto](https://cvr.dev/#/auth/signup) med et aktivt abonnement, som du kan [prøve gratis de første 30 dage](https://cvr.dev/#/prices). 
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing EjerskabshierarkiApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EjerskabshierarkiApiTests : IDisposable
    {
        private EjerskabshierarkiApi instance;

        public EjerskabshierarkiApiTests()
        {
            instance = new EjerskabshierarkiApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EjerskabshierarkiApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' EjerskabshierarkiApi
            //Assert.IsType<EjerskabshierarkiApi>(instance);
        }

        /// <summary>
        /// Test GetCvrDevVirksomhedDatterselskaber
        /// </summary>
        [Fact]
        public void GetCvrDevVirksomhedDatterselskaberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? cvrNummer = null;
            //string? enhedsnummer = null;
            //var response = instance.GetCvrDevVirksomhedDatterselskaber(cvrNummer, enhedsnummer);
            //Assert.IsType<List<VirksomhedOwnership>>(response);
        }

        /// <summary>
        /// Test GetCvrDevVirksomhedEjere
        /// </summary>
        [Fact]
        public void GetCvrDevVirksomhedEjereTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? cvrNummer = null;
            //string? enhedsnummer = null;
            //var response = instance.GetCvrDevVirksomhedEjere(cvrNummer, enhedsnummer);
            //Assert.IsType<List<VirksomhedOwnership>>(response);
        }
    }
}
