/*
 * cvr.dev API dokumentation
 *
 * # Introduktion Velkommen til [cvr.dev](https://cvr.dev)'s HTTP API dokumentation.  Dette dokument beskriver, hvordan du kan benytte vores API til at hente CVR-data. Vi henter og cacher data fra Virks CVR-database en gang i minuttet, så vi altid kan levere så nøjagtig data som muligt.  Udover at være beskrevet på denne sige, er vores API også [beskrevet i OpenAPI 3.0 format](https://docs.cvr.dev/cvrdev_openapi.yml) og som [Postman-dokumentation](https://documenter.getpostman.com/view/13435475/TVejiqUr).  For at benytte vores API skal du have en [cvr.dev-konto](https://cvr.dev/#/auth/signup) med et aktivt abonnement, som du kan [prøve gratis de første 30 dage](https://cvr.dev/#/prices). 
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRDataFraCVRApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Data om Produktionsenheder
        /// </summary>
        /// <remarks>
        /// Dette endpoint returnerer alt data om en produktionsenhed, som den er i CVR. Dette dataformat er bestemt af Virk, ikke af cvr.dev.  ### Data Bemærk feltet &#x60;produktionsEnhedMetadata&#x60;, der indeholder en simplificeret opsummering af resten af data.  Det er meget ofte denne information, man ønsker at benytte.  ### Query parametre **OBS**: *Sendes begge query parametre samtidig, vil kun p_nummer blive brugt.* 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pNummer">P-nummer på produktionsenheden, der søges efter  (optional)</param>
        /// <param name="adresse">Adresse på produktionsenheden, der søges efter  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;Produktionsenhed&gt;</returns>
        List<Produktionsenhed> GetCvrProduktionsenhed(string? pNummer = default(string?), string? adresse = default(string?), int operationIndex = 0);

        /// <summary>
        /// Data om Produktionsenheder
        /// </summary>
        /// <remarks>
        /// Dette endpoint returnerer alt data om en produktionsenhed, som den er i CVR. Dette dataformat er bestemt af Virk, ikke af cvr.dev.  ### Data Bemærk feltet &#x60;produktionsEnhedMetadata&#x60;, der indeholder en simplificeret opsummering af resten af data.  Det er meget ofte denne information, man ønsker at benytte.  ### Query parametre **OBS**: *Sendes begge query parametre samtidig, vil kun p_nummer blive brugt.* 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pNummer">P-nummer på produktionsenheden, der søges efter  (optional)</param>
        /// <param name="adresse">Adresse på produktionsenheden, der søges efter  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;Produktionsenhed&gt;</returns>
        ApiResponse<List<Produktionsenhed>> GetCvrProduktionsenhedWithHttpInfo(string? pNummer = default(string?), string? adresse = default(string?), int operationIndex = 0);
        /// <summary>
        /// Data om Virksomheder
        /// </summary>
        /// <remarks>
        /// Dette endpoint returnerer alt data om en virksomhed, som den er i CVR. Dette dataformat er bestemt af Virk, ikke af cvr.dev.  ### Data Bemærk feltet &#x60;virksomhedMetadata&#x60;, der indeholder en simplificeret opsummering af resten af data.  Det er meget ofte denne information, man ønsker at benytte.  ### Query parametre **OBS**: *Sendes begge query parametre samtidig, vil kun cvr_nummer blive brugt.* 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cvrNummer">CVR-nummer på virksomheden, der søges efter  (optional)</param>
        /// <param name="navn">Navn på virksomheden, der søges efter  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;Virksomhed&gt;</returns>
        List<Virksomhed> GetCvrVirksomhed(string? cvrNummer = default(string?), string? navn = default(string?), int operationIndex = 0);

        /// <summary>
        /// Data om Virksomheder
        /// </summary>
        /// <remarks>
        /// Dette endpoint returnerer alt data om en virksomhed, som den er i CVR. Dette dataformat er bestemt af Virk, ikke af cvr.dev.  ### Data Bemærk feltet &#x60;virksomhedMetadata&#x60;, der indeholder en simplificeret opsummering af resten af data.  Det er meget ofte denne information, man ønsker at benytte.  ### Query parametre **OBS**: *Sendes begge query parametre samtidig, vil kun cvr_nummer blive brugt.* 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cvrNummer">CVR-nummer på virksomheden, der søges efter  (optional)</param>
        /// <param name="navn">Navn på virksomheden, der søges efter  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;Virksomhed&gt;</returns>
        ApiResponse<List<Virksomhed>> GetCvrVirksomhedWithHttpInfo(string? cvrNummer = default(string?), string? navn = default(string?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRDataFraCVRApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Data om Produktionsenheder
        /// </summary>
        /// <remarks>
        /// Dette endpoint returnerer alt data om en produktionsenhed, som den er i CVR. Dette dataformat er bestemt af Virk, ikke af cvr.dev.  ### Data Bemærk feltet &#x60;produktionsEnhedMetadata&#x60;, der indeholder en simplificeret opsummering af resten af data.  Det er meget ofte denne information, man ønsker at benytte.  ### Query parametre **OBS**: *Sendes begge query parametre samtidig, vil kun p_nummer blive brugt.* 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pNummer">P-nummer på produktionsenheden, der søges efter  (optional)</param>
        /// <param name="adresse">Adresse på produktionsenheden, der søges efter  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;Produktionsenhed&gt;</returns>
        System.Threading.Tasks.Task<List<Produktionsenhed>> GetCvrProduktionsenhedAsync(string? pNummer = default(string?), string? adresse = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Data om Produktionsenheder
        /// </summary>
        /// <remarks>
        /// Dette endpoint returnerer alt data om en produktionsenhed, som den er i CVR. Dette dataformat er bestemt af Virk, ikke af cvr.dev.  ### Data Bemærk feltet &#x60;produktionsEnhedMetadata&#x60;, der indeholder en simplificeret opsummering af resten af data.  Det er meget ofte denne information, man ønsker at benytte.  ### Query parametre **OBS**: *Sendes begge query parametre samtidig, vil kun p_nummer blive brugt.* 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pNummer">P-nummer på produktionsenheden, der søges efter  (optional)</param>
        /// <param name="adresse">Adresse på produktionsenheden, der søges efter  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;Produktionsenhed&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Produktionsenhed>>> GetCvrProduktionsenhedWithHttpInfoAsync(string? pNummer = default(string?), string? adresse = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Data om Virksomheder
        /// </summary>
        /// <remarks>
        /// Dette endpoint returnerer alt data om en virksomhed, som den er i CVR. Dette dataformat er bestemt af Virk, ikke af cvr.dev.  ### Data Bemærk feltet &#x60;virksomhedMetadata&#x60;, der indeholder en simplificeret opsummering af resten af data.  Det er meget ofte denne information, man ønsker at benytte.  ### Query parametre **OBS**: *Sendes begge query parametre samtidig, vil kun cvr_nummer blive brugt.* 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cvrNummer">CVR-nummer på virksomheden, der søges efter  (optional)</param>
        /// <param name="navn">Navn på virksomheden, der søges efter  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;Virksomhed&gt;</returns>
        System.Threading.Tasks.Task<List<Virksomhed>> GetCvrVirksomhedAsync(string? cvrNummer = default(string?), string? navn = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Data om Virksomheder
        /// </summary>
        /// <remarks>
        /// Dette endpoint returnerer alt data om en virksomhed, som den er i CVR. Dette dataformat er bestemt af Virk, ikke af cvr.dev.  ### Data Bemærk feltet &#x60;virksomhedMetadata&#x60;, der indeholder en simplificeret opsummering af resten af data.  Det er meget ofte denne information, man ønsker at benytte.  ### Query parametre **OBS**: *Sendes begge query parametre samtidig, vil kun cvr_nummer blive brugt.* 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cvrNummer">CVR-nummer på virksomheden, der søges efter  (optional)</param>
        /// <param name="navn">Navn på virksomheden, der søges efter  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;Virksomhed&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Virksomhed>>> GetCvrVirksomhedWithHttpInfoAsync(string? cvrNummer = default(string?), string? navn = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRDataFraCVRApi : IRDataFraCVRApiSync, IRDataFraCVRApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RDataFraCVRApi : IRDataFraCVRApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RDataFraCVRApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RDataFraCVRApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RDataFraCVRApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RDataFraCVRApi(string basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RDataFraCVRApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RDataFraCVRApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RDataFraCVRApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public RDataFraCVRApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Data om Produktionsenheder Dette endpoint returnerer alt data om en produktionsenhed, som den er i CVR. Dette dataformat er bestemt af Virk, ikke af cvr.dev.  ### Data Bemærk feltet &#x60;produktionsEnhedMetadata&#x60;, der indeholder en simplificeret opsummering af resten af data.  Det er meget ofte denne information, man ønsker at benytte.  ### Query parametre **OBS**: *Sendes begge query parametre samtidig, vil kun p_nummer blive brugt.* 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pNummer">P-nummer på produktionsenheden, der søges efter  (optional)</param>
        /// <param name="adresse">Adresse på produktionsenheden, der søges efter  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;Produktionsenhed&gt;</returns>
        public List<Produktionsenhed> GetCvrProduktionsenhed(string? pNummer = default(string?), string? adresse = default(string?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<List<Produktionsenhed>> localVarResponse = GetCvrProduktionsenhedWithHttpInfo(pNummer, adresse);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Data om Produktionsenheder Dette endpoint returnerer alt data om en produktionsenhed, som den er i CVR. Dette dataformat er bestemt af Virk, ikke af cvr.dev.  ### Data Bemærk feltet &#x60;produktionsEnhedMetadata&#x60;, der indeholder en simplificeret opsummering af resten af data.  Det er meget ofte denne information, man ønsker at benytte.  ### Query parametre **OBS**: *Sendes begge query parametre samtidig, vil kun p_nummer blive brugt.* 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pNummer">P-nummer på produktionsenheden, der søges efter  (optional)</param>
        /// <param name="adresse">Adresse på produktionsenheden, der søges efter  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;Produktionsenhed&gt;</returns>
        public Org.OpenAPITools.Client.ApiResponse<List<Produktionsenhed>> GetCvrProduktionsenhedWithHttpInfo(string? pNummer = default(string?), string? adresse = default(string?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (pNummer != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "p_nummer", pNummer));
            }
            if (adresse != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "adresse", adresse));
            }

            localVarRequestOptions.Operation = "RDataFraCVRApi.GetCvrProduktionsenhed";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (APIKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<Produktionsenhed>>("/api/cvr/produktionsenhed", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCvrProduktionsenhed", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Data om Produktionsenheder Dette endpoint returnerer alt data om en produktionsenhed, som den er i CVR. Dette dataformat er bestemt af Virk, ikke af cvr.dev.  ### Data Bemærk feltet &#x60;produktionsEnhedMetadata&#x60;, der indeholder en simplificeret opsummering af resten af data.  Det er meget ofte denne information, man ønsker at benytte.  ### Query parametre **OBS**: *Sendes begge query parametre samtidig, vil kun p_nummer blive brugt.* 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pNummer">P-nummer på produktionsenheden, der søges efter  (optional)</param>
        /// <param name="adresse">Adresse på produktionsenheden, der søges efter  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;Produktionsenhed&gt;</returns>
        public async System.Threading.Tasks.Task<List<Produktionsenhed>> GetCvrProduktionsenhedAsync(string? pNummer = default(string?), string? adresse = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<List<Produktionsenhed>> localVarResponse = await GetCvrProduktionsenhedWithHttpInfoAsync(pNummer, adresse, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Data om Produktionsenheder Dette endpoint returnerer alt data om en produktionsenhed, som den er i CVR. Dette dataformat er bestemt af Virk, ikke af cvr.dev.  ### Data Bemærk feltet &#x60;produktionsEnhedMetadata&#x60;, der indeholder en simplificeret opsummering af resten af data.  Det er meget ofte denne information, man ønsker at benytte.  ### Query parametre **OBS**: *Sendes begge query parametre samtidig, vil kun p_nummer blive brugt.* 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pNummer">P-nummer på produktionsenheden, der søges efter  (optional)</param>
        /// <param name="adresse">Adresse på produktionsenheden, der søges efter  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;Produktionsenhed&gt;)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<List<Produktionsenhed>>> GetCvrProduktionsenhedWithHttpInfoAsync(string? pNummer = default(string?), string? adresse = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (pNummer != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "p_nummer", pNummer));
            }
            if (adresse != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "adresse", adresse));
            }

            localVarRequestOptions.Operation = "RDataFraCVRApi.GetCvrProduktionsenhed";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (APIKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<Produktionsenhed>>("/api/cvr/produktionsenhed", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCvrProduktionsenhed", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Data om Virksomheder Dette endpoint returnerer alt data om en virksomhed, som den er i CVR. Dette dataformat er bestemt af Virk, ikke af cvr.dev.  ### Data Bemærk feltet &#x60;virksomhedMetadata&#x60;, der indeholder en simplificeret opsummering af resten af data.  Det er meget ofte denne information, man ønsker at benytte.  ### Query parametre **OBS**: *Sendes begge query parametre samtidig, vil kun cvr_nummer blive brugt.* 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cvrNummer">CVR-nummer på virksomheden, der søges efter  (optional)</param>
        /// <param name="navn">Navn på virksomheden, der søges efter  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;Virksomhed&gt;</returns>
        public List<Virksomhed> GetCvrVirksomhed(string? cvrNummer = default(string?), string? navn = default(string?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<List<Virksomhed>> localVarResponse = GetCvrVirksomhedWithHttpInfo(cvrNummer, navn);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Data om Virksomheder Dette endpoint returnerer alt data om en virksomhed, som den er i CVR. Dette dataformat er bestemt af Virk, ikke af cvr.dev.  ### Data Bemærk feltet &#x60;virksomhedMetadata&#x60;, der indeholder en simplificeret opsummering af resten af data.  Det er meget ofte denne information, man ønsker at benytte.  ### Query parametre **OBS**: *Sendes begge query parametre samtidig, vil kun cvr_nummer blive brugt.* 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cvrNummer">CVR-nummer på virksomheden, der søges efter  (optional)</param>
        /// <param name="navn">Navn på virksomheden, der søges efter  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;Virksomhed&gt;</returns>
        public Org.OpenAPITools.Client.ApiResponse<List<Virksomhed>> GetCvrVirksomhedWithHttpInfo(string? cvrNummer = default(string?), string? navn = default(string?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (cvrNummer != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "cvr_nummer", cvrNummer));
            }
            if (navn != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "navn", navn));
            }

            localVarRequestOptions.Operation = "RDataFraCVRApi.GetCvrVirksomhed";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (APIKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<Virksomhed>>("/api/cvr/virksomhed", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCvrVirksomhed", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Data om Virksomheder Dette endpoint returnerer alt data om en virksomhed, som den er i CVR. Dette dataformat er bestemt af Virk, ikke af cvr.dev.  ### Data Bemærk feltet &#x60;virksomhedMetadata&#x60;, der indeholder en simplificeret opsummering af resten af data.  Det er meget ofte denne information, man ønsker at benytte.  ### Query parametre **OBS**: *Sendes begge query parametre samtidig, vil kun cvr_nummer blive brugt.* 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cvrNummer">CVR-nummer på virksomheden, der søges efter  (optional)</param>
        /// <param name="navn">Navn på virksomheden, der søges efter  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;Virksomhed&gt;</returns>
        public async System.Threading.Tasks.Task<List<Virksomhed>> GetCvrVirksomhedAsync(string? cvrNummer = default(string?), string? navn = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<List<Virksomhed>> localVarResponse = await GetCvrVirksomhedWithHttpInfoAsync(cvrNummer, navn, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Data om Virksomheder Dette endpoint returnerer alt data om en virksomhed, som den er i CVR. Dette dataformat er bestemt af Virk, ikke af cvr.dev.  ### Data Bemærk feltet &#x60;virksomhedMetadata&#x60;, der indeholder en simplificeret opsummering af resten af data.  Det er meget ofte denne information, man ønsker at benytte.  ### Query parametre **OBS**: *Sendes begge query parametre samtidig, vil kun cvr_nummer blive brugt.* 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cvrNummer">CVR-nummer på virksomheden, der søges efter  (optional)</param>
        /// <param name="navn">Navn på virksomheden, der søges efter  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;Virksomhed&gt;)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<List<Virksomhed>>> GetCvrVirksomhedWithHttpInfoAsync(string? cvrNummer = default(string?), string? navn = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (cvrNummer != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "cvr_nummer", cvrNummer));
            }
            if (navn != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "navn", navn));
            }

            localVarRequestOptions.Operation = "RDataFraCVRApi.GetCvrVirksomhed";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (APIKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<Virksomhed>>("/api/cvr/virksomhed", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCvrVirksomhed", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
