/*
 * cvr.dev API dokumentation
 *
 * # Introduktion Velkommen til [cvr.dev](https://cvr.dev)'s HTTP API dokumentation.  Dette dokument beskriver, hvordan du kan benytte vores API til at hente CVR-data. Vi henter og cacher data fra Virks CVR-database en gang i minuttet, så vi altid kan levere så nøjagtig data som muligt.  Udover at være beskrevet på denne sige, er vores API også [beskrevet i OpenAPI 3.0 format](https://docs.cvr.dev/cvrdev_openapi.yml) og som [Postman-dokumentation](https://documenter.getpostman.com/view/13435475/TVejiqUr).  For at benytte vores API skal du have en [cvr.dev-konto](https://cvr.dev/#/auth/signup) med et aktivt abonnement, som du kan [prøve gratis de første 30 dage](https://cvr.dev/#/prices). 
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Adresse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdresseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Adresse
        //private Adresse instance;

        public AdresseTests()
        {
            // TODO uncomment below to create an instance of Adresse
            //instance = new Adresse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Adresse
        /// </summary>
        [Fact]
        public void AdresseInstanceTest()
        {
            // TODO uncomment below to test "IsType" Adresse
            //Assert.IsType<Adresse>(instance);
        }

        /// <summary>
        /// Test the property 'AdresseId'
        /// </summary>
        [Fact]
        public void AdresseIdTest()
        {
            // TODO unit test for the property 'AdresseId'
        }

        /// <summary>
        /// Test the property 'BogstavFra'
        /// </summary>
        [Fact]
        public void BogstavFraTest()
        {
            // TODO unit test for the property 'BogstavFra'
        }

        /// <summary>
        /// Test the property 'BogstavTil'
        /// </summary>
        [Fact]
        public void BogstavTilTest()
        {
            // TODO unit test for the property 'BogstavTil'
        }

        /// <summary>
        /// Test the property 'Bynavn'
        /// </summary>
        [Fact]
        public void BynavnTest()
        {
            // TODO unit test for the property 'Bynavn'
        }

        /// <summary>
        /// Test the property 'Conavn'
        /// </summary>
        [Fact]
        public void ConavnTest()
        {
            // TODO unit test for the property 'Conavn'
        }

        /// <summary>
        /// Test the property 'Etage'
        /// </summary>
        [Fact]
        public void EtageTest()
        {
            // TODO unit test for the property 'Etage'
        }

        /// <summary>
        /// Test the property 'Fritekst'
        /// </summary>
        [Fact]
        public void FritekstTest()
        {
            // TODO unit test for the property 'Fritekst'
        }

        /// <summary>
        /// Test the property 'HusnummerFra'
        /// </summary>
        [Fact]
        public void HusnummerFraTest()
        {
            // TODO unit test for the property 'HusnummerFra'
        }

        /// <summary>
        /// Test the property 'HusnummerTil'
        /// </summary>
        [Fact]
        public void HusnummerTilTest()
        {
            // TODO unit test for the property 'HusnummerTil'
        }

        /// <summary>
        /// Test the property 'Kommune'
        /// </summary>
        [Fact]
        public void KommuneTest()
        {
            // TODO unit test for the property 'Kommune'
        }

        /// <summary>
        /// Test the property 'Landekode'
        /// </summary>
        [Fact]
        public void LandekodeTest()
        {
            // TODO unit test for the property 'Landekode'
        }

        /// <summary>
        /// Test the property 'Periode'
        /// </summary>
        [Fact]
        public void PeriodeTest()
        {
            // TODO unit test for the property 'Periode'
        }

        /// <summary>
        /// Test the property 'Postboks'
        /// </summary>
        [Fact]
        public void PostboksTest()
        {
            // TODO unit test for the property 'Postboks'
        }

        /// <summary>
        /// Test the property 'Postdistrikt'
        /// </summary>
        [Fact]
        public void PostdistriktTest()
        {
            // TODO unit test for the property 'Postdistrikt'
        }

        /// <summary>
        /// Test the property 'Postnummer'
        /// </summary>
        [Fact]
        public void PostnummerTest()
        {
            // TODO unit test for the property 'Postnummer'
        }

        /// <summary>
        /// Test the property 'Sidedoer'
        /// </summary>
        [Fact]
        public void SidedoerTest()
        {
            // TODO unit test for the property 'Sidedoer'
        }

        /// <summary>
        /// Test the property 'SidstOpdateret'
        /// </summary>
        [Fact]
        public void SidstOpdateretTest()
        {
            // TODO unit test for the property 'SidstOpdateret'
        }

        /// <summary>
        /// Test the property 'SidstValideret'
        /// </summary>
        [Fact]
        public void SidstValideretTest()
        {
            // TODO unit test for the property 'SidstValideret'
        }

        /// <summary>
        /// Test the property 'Vejkode'
        /// </summary>
        [Fact]
        public void VejkodeTest()
        {
            // TODO unit test for the property 'Vejkode'
        }

        /// <summary>
        /// Test the property 'Vejnavn'
        /// </summary>
        [Fact]
        public void VejnavnTest()
        {
            // TODO unit test for the property 'Vejnavn'
        }
    }
}
