/*
 * cvr.dev API dokumentation
 *
 * # Introduktion Velkommen til [cvr.dev](https://cvr.dev)'s HTTP API dokumentation.  Dette dokument beskriver, hvordan du kan benytte vores API til at hente CVR-data. Vi henter og cacher data fra Virks CVR-database en gang i minuttet, så vi altid kan levere så nøjagtig data som muligt.  Udover at være beskrevet på denne sige, er vores API også [beskrevet i OpenAPI 3.0 format](https://docs.cvr.dev/cvrdev_openapi.yml) og som [Postman-dokumentation](https://documenter.getpostman.com/view/13435475/TVejiqUr).  For at benytte vores API skal du have en [cvr.dev-konto](https://cvr.dev/#/auth/signup) med et aktivt abonnement, som du kan [prøve gratis de første 30 dage](https://cvr.dev/#/prices). 
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Organisation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrganisationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Organisation
        //private Organisation instance;

        public OrganisationTests()
        {
            // TODO uncomment below to create an instance of Organisation
            //instance = new Organisation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Organisation
        /// </summary>
        [Fact]
        public void OrganisationInstanceTest()
        {
            // TODO uncomment below to test "IsType" Organisation
            //Assert.IsType<Organisation>(instance);
        }

        /// <summary>
        /// Test the property 'Attributter'
        /// </summary>
        [Fact]
        public void AttributterTest()
        {
            // TODO unit test for the property 'Attributter'
        }

        /// <summary>
        /// Test the property 'EnhedsNummerOrganisation'
        /// </summary>
        [Fact]
        public void EnhedsNummerOrganisationTest()
        {
            // TODO unit test for the property 'EnhedsNummerOrganisation'
        }

        /// <summary>
        /// Test the property 'Hovedtype'
        /// </summary>
        [Fact]
        public void HovedtypeTest()
        {
            // TODO unit test for the property 'Hovedtype'
        }

        /// <summary>
        /// Test the property 'MedlemsData'
        /// </summary>
        [Fact]
        public void MedlemsDataTest()
        {
            // TODO unit test for the property 'MedlemsData'
        }

        /// <summary>
        /// Test the property 'OrganisationsNavn'
        /// </summary>
        [Fact]
        public void OrganisationsNavnTest()
        {
            // TODO unit test for the property 'OrganisationsNavn'
        }
    }
}
