/*
 * cvr.dev API dokumentation
 *
 * # Introduktion Velkommen til [cvr.dev](https://cvr.dev)'s HTTP API dokumentation.  Dette dokument beskriver, hvordan du kan benytte vores API til at hente CVR-data. Vi henter og cacher data fra Virks CVR-database en gang i minuttet, så vi altid kan levere så nøjagtig data som muligt.  Udover at være beskrevet på denne sige, er vores API også [beskrevet i OpenAPI 3.0 format](https://docs.cvr.dev/cvrdev_openapi.yml) og som [Postman-dokumentation](https://documenter.getpostman.com/view/13435475/TVejiqUr).  For at benytte vores API skal du have en [cvr.dev-konto](https://cvr.dev/#/auth/signup) med et aktivt abonnement, som du kan [prøve gratis de første 30 dage](https://cvr.dev/#/prices). 
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Spaltning
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpaltningTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Spaltning
        //private Spaltning instance;

        public SpaltningTests()
        {
            // TODO uncomment below to create an instance of Spaltning
            //instance = new Spaltning();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Spaltning
        /// </summary>
        [Fact]
        public void SpaltningInstanceTest()
        {
            // TODO uncomment below to test "IsType" Spaltning
            //Assert.IsType<Spaltning>(instance);
        }

        /// <summary>
        /// Test the property 'EnhedsNummerOrganisation'
        /// </summary>
        [Fact]
        public void EnhedsNummerOrganisationTest()
        {
            // TODO unit test for the property 'EnhedsNummerOrganisation'
        }

        /// <summary>
        /// Test the property 'Indgaaende'
        /// </summary>
        [Fact]
        public void IndgaaendeTest()
        {
            // TODO unit test for the property 'Indgaaende'
        }

        /// <summary>
        /// Test the property 'OrganisationsNavn'
        /// </summary>
        [Fact]
        public void OrganisationsNavnTest()
        {
            // TODO unit test for the property 'OrganisationsNavn'
        }

        /// <summary>
        /// Test the property 'Udgaaende'
        /// </summary>
        [Fact]
        public void UdgaaendeTest()
        {
            // TODO unit test for the property 'Udgaaende'
        }
    }
}
