/*
 * cvr.dev API dokumentation
 *
 * # Introduktion Velkommen til [cvr.dev](https://cvr.dev)'s HTTP API dokumentation.  Dette dokument beskriver, hvordan du kan benytte vores API til at hente CVR-data. Vi henter og cacher data fra Virks CVR-database en gang i minuttet, så vi altid kan levere så nøjagtig data som muligt.  Udover at være beskrevet på denne sige, er vores API også [beskrevet i OpenAPI 3.0 format](https://docs.cvr.dev/cvrdev_openapi.yml) og som [Postman-dokumentation](https://documenter.getpostman.com/view/13435475/TVejiqUr).  For at benytte vores API skal du have en [cvr.dev-konto](https://cvr.dev/#/auth/signup) med et aktivt abonnement, som du kan [prøve gratis de første 30 dage](https://cvr.dev/#/prices). 
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing VirksomhedVirksomhedMetadataNyesteMaanedsbeskaeftigelse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VirksomhedVirksomhedMetadataNyesteMaanedsbeskaeftigelseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VirksomhedVirksomhedMetadataNyesteMaanedsbeskaeftigelse
        //private VirksomhedVirksomhedMetadataNyesteMaanedsbeskaeftigelse instance;

        public VirksomhedVirksomhedMetadataNyesteMaanedsbeskaeftigelseTests()
        {
            // TODO uncomment below to create an instance of VirksomhedVirksomhedMetadataNyesteMaanedsbeskaeftigelse
            //instance = new VirksomhedVirksomhedMetadataNyesteMaanedsbeskaeftigelse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VirksomhedVirksomhedMetadataNyesteMaanedsbeskaeftigelse
        /// </summary>
        [Fact]
        public void VirksomhedVirksomhedMetadataNyesteMaanedsbeskaeftigelseInstanceTest()
        {
            // TODO uncomment below to test "IsType" VirksomhedVirksomhedMetadataNyesteMaanedsbeskaeftigelse
            //Assert.IsType<VirksomhedVirksomhedMetadataNyesteMaanedsbeskaeftigelse>(instance);
        }

        /// <summary>
        /// Test the property 'Aar'
        /// </summary>
        [Fact]
        public void AarTest()
        {
            // TODO unit test for the property 'Aar'
        }

        /// <summary>
        /// Test the property 'AntalAarsvaerk'
        /// </summary>
        [Fact]
        public void AntalAarsvaerkTest()
        {
            // TODO unit test for the property 'AntalAarsvaerk'
        }

        /// <summary>
        /// Test the property 'AntalAnsatte'
        /// </summary>
        [Fact]
        public void AntalAnsatteTest()
        {
            // TODO unit test for the property 'AntalAnsatte'
        }

        /// <summary>
        /// Test the property 'IntervalKodeAntalAarsvaerk'
        /// </summary>
        [Fact]
        public void IntervalKodeAntalAarsvaerkTest()
        {
            // TODO unit test for the property 'IntervalKodeAntalAarsvaerk'
        }

        /// <summary>
        /// Test the property 'IntervalKodeAntalAnsatte'
        /// </summary>
        [Fact]
        public void IntervalKodeAntalAnsatteTest()
        {
            // TODO unit test for the property 'IntervalKodeAntalAnsatte'
        }

        /// <summary>
        /// Test the property 'Maaned'
        /// </summary>
        [Fact]
        public void MaanedTest()
        {
            // TODO unit test for the property 'Maaned'
        }

        /// <summary>
        /// Test the property 'SidstOpdateret'
        /// </summary>
        [Fact]
        public void SidstOpdateretTest()
        {
            // TODO unit test for the property 'SidstOpdateret'
        }
    }
}
