/*
 * cvr.dev API dokumentation
 *
 * # Introduktion Velkommen til [cvr.dev](https://cvr.dev)'s HTTP API dokumentation.  Dette dokument beskriver, hvordan du kan benytte vores API til at hente CVR-data. Vi henter og cacher data fra Virks CVR-database en gang i minuttet, så vi altid kan levere så nøjagtig data som muligt.  Udover at være beskrevet på denne sige, er vores API også [beskrevet i OpenAPI 3.0 format](https://docs.cvr.dev/cvrdev_openapi.yml) og som [Postman-dokumentation](https://documenter.getpostman.com/view/13435475/TVejiqUr).  For at benytte vores API skal du have en [cvr.dev-konto](https://cvr.dev/#/auth/signup) med et aktivt abonnement, som du kan [prøve gratis de første 30 dage](https://cvr.dev/#/prices). 
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing VirksomhedDeltagerRelationInnerDeltager
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VirksomhedDeltagerRelationInnerDeltagerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VirksomhedDeltagerRelationInnerDeltager
        //private VirksomhedDeltagerRelationInnerDeltager instance;

        public VirksomhedDeltagerRelationInnerDeltagerTests()
        {
            // TODO uncomment below to create an instance of VirksomhedDeltagerRelationInnerDeltager
            //instance = new VirksomhedDeltagerRelationInnerDeltager();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VirksomhedDeltagerRelationInnerDeltager
        /// </summary>
        [Fact]
        public void VirksomhedDeltagerRelationInnerDeltagerInstanceTest()
        {
            // TODO uncomment below to test "IsType" VirksomhedDeltagerRelationInnerDeltager
            //Assert.IsType<VirksomhedDeltagerRelationInnerDeltager>(instance);
        }

        /// <summary>
        /// Test the property 'AdresseHemmelig'
        /// </summary>
        [Fact]
        public void AdresseHemmeligTest()
        {
            // TODO unit test for the property 'AdresseHemmelig'
        }

        /// <summary>
        /// Test the property 'AdresseHemmeligUndtagelse'
        /// </summary>
        [Fact]
        public void AdresseHemmeligUndtagelseTest()
        {
            // TODO unit test for the property 'AdresseHemmeligUndtagelse'
        }

        /// <summary>
        /// Test the property 'AdresseOpdateringOphoert'
        /// </summary>
        [Fact]
        public void AdresseOpdateringOphoertTest()
        {
            // TODO unit test for the property 'AdresseOpdateringOphoert'
        }

        /// <summary>
        /// Test the property 'Beliggenhedsadresse'
        /// </summary>
        [Fact]
        public void BeliggenhedsadresseTest()
        {
            // TODO unit test for the property 'Beliggenhedsadresse'
        }

        /// <summary>
        /// Test the property 'EnhedsNummer'
        /// </summary>
        [Fact]
        public void EnhedsNummerTest()
        {
            // TODO unit test for the property 'EnhedsNummer'
        }

        /// <summary>
        /// Test the property 'Enhedstype'
        /// </summary>
        [Fact]
        public void EnhedstypeTest()
        {
            // TODO unit test for the property 'Enhedstype'
        }

        /// <summary>
        /// Test the property 'Forretningsnoegle'
        /// </summary>
        [Fact]
        public void ForretningsnoegleTest()
        {
            // TODO unit test for the property 'Forretningsnoegle'
        }

        /// <summary>
        /// Test the property 'Navne'
        /// </summary>
        [Fact]
        public void NavneTest()
        {
            // TODO unit test for the property 'Navne'
        }

        /// <summary>
        /// Test the property 'Postadresse'
        /// </summary>
        [Fact]
        public void PostadresseTest()
        {
            // TODO unit test for the property 'Postadresse'
        }

        /// <summary>
        /// Test the property 'SidstIndlaest'
        /// </summary>
        [Fact]
        public void SidstIndlaestTest()
        {
            // TODO unit test for the property 'SidstIndlaest'
        }

        /// <summary>
        /// Test the property 'SidstOpdateret'
        /// </summary>
        [Fact]
        public void SidstOpdateretTest()
        {
            // TODO unit test for the property 'SidstOpdateret'
        }
    }
}
