/*
 * cvr.dev API dokumentation
 *
 * # Introduktion Velkommen til [cvr.dev](https://cvr.dev)'s HTTP API dokumentation.  Dette dokument beskriver, hvordan du kan benytte vores API til at hente CVR-data. Vi henter og cacher data fra Virks CVR-database en gang i minuttet, så vi altid kan levere så nøjagtig data som muligt.  Udover at være beskrevet på denne sige, er vores API også [beskrevet i OpenAPI 3.0 format](https://docs.cvr.dev/cvrdev_openapi.yml) og som [Postman-dokumentation](https://documenter.getpostman.com/view/13435475/TVejiqUr).  For at benytte vores API skal du have en [cvr.dev-konto](https://cvr.dev/#/auth/signup) med et aktivt abonnement, som du kan [prøve gratis de første 30 dage](https://cvr.dev/#/prices). 
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing VirksomhedVirksomhedMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VirksomhedVirksomhedMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VirksomhedVirksomhedMetadata
        //private VirksomhedVirksomhedMetadata instance;

        public VirksomhedVirksomhedMetadataTests()
        {
            // TODO uncomment below to create an instance of VirksomhedVirksomhedMetadata
            //instance = new VirksomhedVirksomhedMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VirksomhedVirksomhedMetadata
        /// </summary>
        [Fact]
        public void VirksomhedVirksomhedMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" VirksomhedVirksomhedMetadata
            //Assert.IsType<VirksomhedVirksomhedMetadata>(instance);
        }

        /// <summary>
        /// Test the property 'AntalPenheder'
        /// </summary>
        [Fact]
        public void AntalPenhederTest()
        {
            // TODO unit test for the property 'AntalPenheder'
        }

        /// <summary>
        /// Test the property 'NyesteAarsbeskaeftigelse'
        /// </summary>
        [Fact]
        public void NyesteAarsbeskaeftigelseTest()
        {
            // TODO unit test for the property 'NyesteAarsbeskaeftigelse'
        }

        /// <summary>
        /// Test the property 'NyesteBeliggenhedsadresse'
        /// </summary>
        [Fact]
        public void NyesteBeliggenhedsadresseTest()
        {
            // TODO unit test for the property 'NyesteBeliggenhedsadresse'
        }

        /// <summary>
        /// Test the property 'NyesteBibranche1'
        /// </summary>
        [Fact]
        public void NyesteBibranche1Test()
        {
            // TODO unit test for the property 'NyesteBibranche1'
        }

        /// <summary>
        /// Test the property 'NyesteBibranche2'
        /// </summary>
        [Fact]
        public void NyesteBibranche2Test()
        {
            // TODO unit test for the property 'NyesteBibranche2'
        }

        /// <summary>
        /// Test the property 'NyesteBibranche3'
        /// </summary>
        [Fact]
        public void NyesteBibranche3Test()
        {
            // TODO unit test for the property 'NyesteBibranche3'
        }

        /// <summary>
        /// Test the property 'NyesteBinavne'
        /// </summary>
        [Fact]
        public void NyesteBinavneTest()
        {
            // TODO unit test for the property 'NyesteBinavne'
        }

        /// <summary>
        /// Test the property 'NyesteErstMaanedsbeskaeftigelse'
        /// </summary>
        [Fact]
        public void NyesteErstMaanedsbeskaeftigelseTest()
        {
            // TODO unit test for the property 'NyesteErstMaanedsbeskaeftigelse'
        }

        /// <summary>
        /// Test the property 'NyesteHovedbranche'
        /// </summary>
        [Fact]
        public void NyesteHovedbrancheTest()
        {
            // TODO unit test for the property 'NyesteHovedbranche'
        }

        /// <summary>
        /// Test the property 'NyesteKontaktoplysninger'
        /// </summary>
        [Fact]
        public void NyesteKontaktoplysningerTest()
        {
            // TODO unit test for the property 'NyesteKontaktoplysninger'
        }

        /// <summary>
        /// Test the property 'NyesteKvartalsbeskaeftigelse'
        /// </summary>
        [Fact]
        public void NyesteKvartalsbeskaeftigelseTest()
        {
            // TODO unit test for the property 'NyesteKvartalsbeskaeftigelse'
        }

        /// <summary>
        /// Test the property 'NyesteMaanedsbeskaeftigelse'
        /// </summary>
        [Fact]
        public void NyesteMaanedsbeskaeftigelseTest()
        {
            // TODO unit test for the property 'NyesteMaanedsbeskaeftigelse'
        }

        /// <summary>
        /// Test the property 'NyesteNavn'
        /// </summary>
        [Fact]
        public void NyesteNavnTest()
        {
            // TODO unit test for the property 'NyesteNavn'
        }

        /// <summary>
        /// Test the property 'NyesteStatus'
        /// </summary>
        [Fact]
        public void NyesteStatusTest()
        {
            // TODO unit test for the property 'NyesteStatus'
        }

        /// <summary>
        /// Test the property 'NyesteVirksomhedsform'
        /// </summary>
        [Fact]
        public void NyesteVirksomhedsformTest()
        {
            // TODO unit test for the property 'NyesteVirksomhedsform'
        }
    }
}
