/*
 * cvr.dev API dokumentation
 *
 * # Introduktion Velkommen til [cvr.dev](https://cvr.dev)'s HTTP API dokumentation.  Dette dokument beskriver, hvordan du kan benytte vores API til at hente CVR-data. Vi henter og cacher data fra Virks CVR-database en gang i minuttet, så vi altid kan levere så nøjagtig data som muligt.  Udover at være beskrevet på denne sige, er vores API også [beskrevet i OpenAPI 3.0 format](https://docs.cvr.dev/cvrdev_openapi.yml) og som [Postman-dokumentation](https://documenter.getpostman.com/view/13435475/TVejiqUr).  For at benytte vores API skal du have en [cvr.dev-konto](https://cvr.dev/#/auth/signup) med et aktivt abonnement, som du kan [prøve gratis de første 30 dage](https://cvr.dev/#/prices). 
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Virksomhed
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VirksomhedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Virksomhed
        //private Virksomhed instance;

        public VirksomhedTests()
        {
            // TODO uncomment below to create an instance of Virksomhed
            //instance = new Virksomhed();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Virksomhed
        /// </summary>
        [Fact]
        public void VirksomhedInstanceTest()
        {
            // TODO uncomment below to test "IsType" Virksomhed
            //Assert.IsType<Virksomhed>(instance);
        }

        /// <summary>
        /// Test the property 'Aarsbeskaeftigelse'
        /// </summary>
        [Fact]
        public void AarsbeskaeftigelseTest()
        {
            // TODO unit test for the property 'Aarsbeskaeftigelse'
        }

        /// <summary>
        /// Test the property 'Attributter'
        /// </summary>
        [Fact]
        public void AttributterTest()
        {
            // TODO unit test for the property 'Attributter'
        }

        /// <summary>
        /// Test the property 'Beliggenhedsadresse'
        /// </summary>
        [Fact]
        public void BeliggenhedsadresseTest()
        {
            // TODO unit test for the property 'Beliggenhedsadresse'
        }

        /// <summary>
        /// Test the property 'Bibranche1'
        /// </summary>
        [Fact]
        public void Bibranche1Test()
        {
            // TODO unit test for the property 'Bibranche1'
        }

        /// <summary>
        /// Test the property 'Bibranche2'
        /// </summary>
        [Fact]
        public void Bibranche2Test()
        {
            // TODO unit test for the property 'Bibranche2'
        }

        /// <summary>
        /// Test the property 'Bibranche3'
        /// </summary>
        [Fact]
        public void Bibranche3Test()
        {
            // TODO unit test for the property 'Bibranche3'
        }

        /// <summary>
        /// Test the property 'Binavne'
        /// </summary>
        [Fact]
        public void BinavneTest()
        {
            // TODO unit test for the property 'Binavne'
        }

        /// <summary>
        /// Test the property 'BrancheAnsvarskode'
        /// </summary>
        [Fact]
        public void BrancheAnsvarskodeTest()
        {
            // TODO unit test for the property 'BrancheAnsvarskode'
        }

        /// <summary>
        /// Test the property 'CvrNummer'
        /// </summary>
        [Fact]
        public void CvrNummerTest()
        {
            // TODO unit test for the property 'CvrNummer'
        }

        /// <summary>
        /// Test the property 'DataAdgang'
        /// </summary>
        [Fact]
        public void DataAdgangTest()
        {
            // TODO unit test for the property 'DataAdgang'
        }

        /// <summary>
        /// Test the property 'DeltagerRelation'
        /// </summary>
        [Fact]
        public void DeltagerRelationTest()
        {
            // TODO unit test for the property 'DeltagerRelation'
        }

        /// <summary>
        /// Test the property 'ElektroniskPost'
        /// </summary>
        [Fact]
        public void ElektroniskPostTest()
        {
            // TODO unit test for the property 'ElektroniskPost'
        }

        /// <summary>
        /// Test the property 'EnhedsNummer'
        /// </summary>
        [Fact]
        public void EnhedsNummerTest()
        {
            // TODO unit test for the property 'EnhedsNummer'
        }

        /// <summary>
        /// Test the property 'Enhedstype'
        /// </summary>
        [Fact]
        public void EnhedstypeTest()
        {
            // TODO unit test for the property 'Enhedstype'
        }

        /// <summary>
        /// Test the property 'FejlBeskrivelse'
        /// </summary>
        [Fact]
        public void FejlBeskrivelseTest()
        {
            // TODO unit test for the property 'FejlBeskrivelse'
        }

        /// <summary>
        /// Test the property 'FejlRegistreret'
        /// </summary>
        [Fact]
        public void FejlRegistreretTest()
        {
            // TODO unit test for the property 'FejlRegistreret'
        }

        /// <summary>
        /// Test the property 'FejlVedIndlaesning'
        /// </summary>
        [Fact]
        public void FejlVedIndlaesningTest()
        {
            // TODO unit test for the property 'FejlVedIndlaesning'
        }

        /// <summary>
        /// Test the property 'Fusioner'
        /// </summary>
        [Fact]
        public void FusionerTest()
        {
            // TODO unit test for the property 'Fusioner'
        }

        /// <summary>
        /// Test the property 'Hjemmeside'
        /// </summary>
        [Fact]
        public void HjemmesideTest()
        {
            // TODO unit test for the property 'Hjemmeside'
        }

        /// <summary>
        /// Test the property 'Hovedbranche'
        /// </summary>
        [Fact]
        public void HovedbrancheTest()
        {
            // TODO unit test for the property 'Hovedbranche'
        }

        /// <summary>
        /// Test the property 'Kvartalsbeskaeftigelse'
        /// </summary>
        [Fact]
        public void KvartalsbeskaeftigelseTest()
        {
            // TODO unit test for the property 'Kvartalsbeskaeftigelse'
        }

        /// <summary>
        /// Test the property 'Livsforloeb'
        /// </summary>
        [Fact]
        public void LivsforloebTest()
        {
            // TODO unit test for the property 'Livsforloeb'
        }

        /// <summary>
        /// Test the property 'Maanedsbeskaeftigelse'
        /// </summary>
        [Fact]
        public void MaanedsbeskaeftigelseTest()
        {
            // TODO unit test for the property 'Maanedsbeskaeftigelse'
        }

        /// <summary>
        /// Test the property 'NaermesteFremtidigeDato'
        /// </summary>
        [Fact]
        public void NaermesteFremtidigeDatoTest()
        {
            // TODO unit test for the property 'NaermesteFremtidigeDato'
        }

        /// <summary>
        /// Test the property 'Navne'
        /// </summary>
        [Fact]
        public void NavneTest()
        {
            // TODO unit test for the property 'Navne'
        }

        /// <summary>
        /// Test the property 'ObligatoriskEmail'
        /// </summary>
        [Fact]
        public void ObligatoriskEmailTest()
        {
            // TODO unit test for the property 'ObligatoriskEmail'
        }

        /// <summary>
        /// Test the property 'Penheder'
        /// </summary>
        [Fact]
        public void PenhederTest()
        {
            // TODO unit test for the property 'Penheder'
        }

        /// <summary>
        /// Test the property 'Postadresse'
        /// </summary>
        [Fact]
        public void PostadresseTest()
        {
            // TODO unit test for the property 'Postadresse'
        }

        /// <summary>
        /// Test the property 'RegNummer'
        /// </summary>
        [Fact]
        public void RegNummerTest()
        {
            // TODO unit test for the property 'RegNummer'
        }

        /// <summary>
        /// Test the property 'Reklamebeskyttet'
        /// </summary>
        [Fact]
        public void ReklamebeskyttetTest()
        {
            // TODO unit test for the property 'Reklamebeskyttet'
        }

        /// <summary>
        /// Test the property 'SamtId'
        /// </summary>
        [Fact]
        public void SamtIdTest()
        {
            // TODO unit test for the property 'SamtId'
        }

        /// <summary>
        /// Test the property 'SekundaertTelefaxNummer'
        /// </summary>
        [Fact]
        public void SekundaertTelefaxNummerTest()
        {
            // TODO unit test for the property 'SekundaertTelefaxNummer'
        }

        /// <summary>
        /// Test the property 'SekundaertTelefonNummer'
        /// </summary>
        [Fact]
        public void SekundaertTelefonNummerTest()
        {
            // TODO unit test for the property 'SekundaertTelefonNummer'
        }

        /// <summary>
        /// Test the property 'SidstIndlaest'
        /// </summary>
        [Fact]
        public void SidstIndlaestTest()
        {
            // TODO unit test for the property 'SidstIndlaest'
        }

        /// <summary>
        /// Test the property 'SidstOpdateret'
        /// </summary>
        [Fact]
        public void SidstOpdateretTest()
        {
            // TODO unit test for the property 'SidstOpdateret'
        }

        /// <summary>
        /// Test the property 'Spaltninger'
        /// </summary>
        [Fact]
        public void SpaltningerTest()
        {
            // TODO unit test for the property 'Spaltninger'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'TelefaxNummer'
        /// </summary>
        [Fact]
        public void TelefaxNummerTest()
        {
            // TODO unit test for the property 'TelefaxNummer'
        }

        /// <summary>
        /// Test the property 'TelefonNummer'
        /// </summary>
        [Fact]
        public void TelefonNummerTest()
        {
            // TODO unit test for the property 'TelefonNummer'
        }

        /// <summary>
        /// Test the property 'VirkningsAktoer'
        /// </summary>
        [Fact]
        public void VirkningsAktoerTest()
        {
            // TODO unit test for the property 'VirkningsAktoer'
        }

        /// <summary>
        /// Test the property 'VirksomhedMetadata'
        /// </summary>
        [Fact]
        public void VirksomhedMetadataTest()
        {
            // TODO unit test for the property 'VirksomhedMetadata'
        }

        /// <summary>
        /// Test the property 'Virksomhedsstatus'
        /// </summary>
        [Fact]
        public void VirksomhedsstatusTest()
        {
            // TODO unit test for the property 'Virksomhedsstatus'
        }
    }
}
