/*
 * cvr.dev API dokumentation
 *
 * # Introduktion Velkommen til [cvr.dev](https://cvr.dev)'s HTTP API dokumentation.  Dette dokument beskriver, hvordan du kan benytte vores API til at hente CVR-data. Vi henter og cacher data fra Virks CVR-database en gang i minuttet, så vi altid kan levere så nøjagtig data som muligt.  Udover at være beskrevet på denne sige, er vores API også [beskrevet i OpenAPI 3.0 format](https://docs.cvr.dev/cvrdev_openapi.yml) og som [Postman-dokumentation](https://documenter.getpostman.com/view/13435475/TVejiqUr).  For at benytte vores API skal du have en [cvr.dev-konto](https://cvr.dev/#/auth/signup) med et aktivt abonnement, som du kan [prøve gratis de første 30 dage](https://cvr.dev/#/prices). 
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing VirksomhedOwnership
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VirksomhedOwnershipTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VirksomhedOwnership
        //private VirksomhedOwnership instance;

        public VirksomhedOwnershipTests()
        {
            // TODO uncomment below to create an instance of VirksomhedOwnership
            //instance = new VirksomhedOwnership();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VirksomhedOwnership
        /// </summary>
        [Fact]
        public void VirksomhedOwnershipInstanceTest()
        {
            // TODO uncomment below to test "IsType" VirksomhedOwnership
            //Assert.IsType<VirksomhedOwnership>(instance);
        }

        /// <summary>
        /// Test the property 'EjerEnhedsnummer'
        /// </summary>
        [Fact]
        public void EjerEnhedsnummerTest()
        {
            // TODO unit test for the property 'EjerEnhedsnummer'
        }

        /// <summary>
        /// Test the property 'EjerNavn'
        /// </summary>
        [Fact]
        public void EjerNavnTest()
        {
            // TODO unit test for the property 'EjerNavn'
        }

        /// <summary>
        /// Test the property 'EjerCvrNummer'
        /// </summary>
        [Fact]
        public void EjerCvrNummerTest()
        {
            // TODO unit test for the property 'EjerCvrNummer'
        }

        /// <summary>
        /// Test the property 'EjerEnhedstype'
        /// </summary>
        [Fact]
        public void EjerEnhedstypeTest()
        {
            // TODO unit test for the property 'EjerEnhedstype'
        }

        /// <summary>
        /// Test the property 'Ejerforhold'
        /// </summary>
        [Fact]
        public void EjerforholdTest()
        {
            // TODO unit test for the property 'Ejerforhold'
        }

        /// <summary>
        /// Test the property 'VirksomhedEnhedsnummer'
        /// </summary>
        [Fact]
        public void VirksomhedEnhedsnummerTest()
        {
            // TODO unit test for the property 'VirksomhedEnhedsnummer'
        }

        /// <summary>
        /// Test the property 'VirksomhedNavn'
        /// </summary>
        [Fact]
        public void VirksomhedNavnTest()
        {
            // TODO unit test for the property 'VirksomhedNavn'
        }

        /// <summary>
        /// Test the property 'VirksomhedCvrNummer'
        /// </summary>
        [Fact]
        public void VirksomhedCvrNummerTest()
        {
            // TODO unit test for the property 'VirksomhedCvrNummer'
        }

        /// <summary>
        /// Test the property 'Virksomhedsform'
        /// </summary>
        [Fact]
        public void VirksomhedsformTest()
        {
            // TODO unit test for the property 'Virksomhedsform'
        }

        /// <summary>
        /// Test the property 'Ejerandel'
        /// </summary>
        [Fact]
        public void EjerandelTest()
        {
            // TODO unit test for the property 'Ejerandel'
        }

        /// <summary>
        /// Test the property 'EjerandelGyldigFra'
        /// </summary>
        [Fact]
        public void EjerandelGyldigFraTest()
        {
            // TODO unit test for the property 'EjerandelGyldigFra'
        }

        /// <summary>
        /// Test the property 'EjerandelGyldigTil'
        /// </summary>
        [Fact]
        public void EjerandelGyldigTilTest()
        {
            // TODO unit test for the property 'EjerandelGyldigTil'
        }

        /// <summary>
        /// Test the property 'Stemmeret'
        /// </summary>
        [Fact]
        public void StemmeretTest()
        {
            // TODO unit test for the property 'Stemmeret'
        }

        /// <summary>
        /// Test the property 'StemmeretGyldigFra'
        /// </summary>
        [Fact]
        public void StemmeretGyldigFraTest()
        {
            // TODO unit test for the property 'StemmeretGyldigFra'
        }

        /// <summary>
        /// Test the property 'StemmeretGyldigTil'
        /// </summary>
        [Fact]
        public void StemmeretGyldigTilTest()
        {
            // TODO unit test for the property 'StemmeretGyldigTil'
        }

        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Fact]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
    }
}
